spring.application.name=worker
MANAGER_URL=http://manager:8080

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

spring.data.redis.host=redis
spring.data.redis.port=6379

rabbitmq.worker_to_manager_queue.name=worker-to-manager-queue
rabbitmq.manager_to_worker_queue.name=manager-to-worker-queue
rabbitmq.exchange.name=direct-exchange
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=1
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.simple.acknowledge-mode=manual